portainer:
  image: 'portainer/portainer'
  container_name: Portainer
  restart: always
  ports:
    - "9000:9000"
  net: "host"
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - 'portainer_data:/data portainer/portainer'

